### ISSUE TITLE
Fraud-detector can't to start

### ISSUE THREAD

**Issue by fastchain** [bobanetwork/boba_legacy#1268]
## Issue Type

```
[X] bug report
[ ] feature request
```

## Current Behavior
Fraud-detector fails to run

## Expected Behavior
Fraud detector works

## Steps to Reproduce

Follow this  manual 

https://github.com/bobanetwork/boba/tree/develop/boba_community/fraud-detector

till the step 

```
curl -H "Content-Type: application/json" -T state-dumps/mainnet/addresses.json http://localhost:8080/addresses.json
```

after it  container fraud-detector-fraud-detector-1 collapses with the following trace

```
raud-detector-fraud-detector-1   | DEBUG 20231018T064253 Connected to VERIFIER_WEB3_URL
fraud-detector-fraud-detector-1   | Traceback (most recent call last):
fraud-detector-fraud-detector-1   |   File "./fraud-detector.py", line 134, in <module>
fraud-detector-fraud-detector-1   |     scc_addr = address_manager.functions.getAddress("StateCommitmentChain").call()
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/contract.py", line 970, in call
fraud-detector-fraud-detector-1   |     return call_contract_function(
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/contract.py", line 1564, in call_contract_function
fraud-detector-fraud-detector-1   |     return_data = web3.eth.call(
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/module.py", line 57, in caller
fraud-detector-fraud-detector-1   |     result = w3.manager.request_blocking(method_str,
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
fraud-detector-fraud-detector-1   |     response = self._make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
fraud-detector-fraud-detector-1   |     return request_func(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
fraud-detector-fraud-detector-1   |     return make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 87, in middleware
fraud-detector-fraud-detector-1   |     web3_formatters_builder(w3, method),
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/validation.py", line 140, in build_method_validators
fraud-detector-fraud-detector-1   |     w3_chain_id = w3.eth.chain_id
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/eth.py", line 632, in chain_id
fraud-detector-fraud-detector-1   |     return self._chain_id()
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/module.py", line 57, in caller
fraud-detector-fraud-detector-1   |     result = w3.manager.request_blocking(method_str,
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
fraud-detector-fraud-detector-1   |     response = self._make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
fraud-detector-fraud-detector-1   |     return request_func(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
fraud-detector-fraud-detector-1   |     return make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
fraud-detector-fraud-detector-1   |     return make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     
fraud-detector-fraud-detector-1   | response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/exception_retry_request.py", line 114, in middleware
fraud-detector-fraud-detector-1   |     return make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/providers/rpc.py", line 88, in make_request
fraud-detector-fraud-detector-1   |     raw_response = make_post_request(
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/_utils/request.py", line 113, in make_post_request
fraud-detector-fraud-detector-1   |     response.raise_for_status()
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
fraud-detector-fraud-detector-1   |     raise HTTPError(http_error_msg, response=self)
fraud-detector-fraud-detector-1   | requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://mainnet.gateway.tenderly.co/
fraud-detector-fraud-detector-1 exited with code 1
```

## Suggested Fix

Avoid many request in the code somehow. 
Or provide a reliable RPC.

**Comment by InoMurko** [comment]
Thank you for reporting this. @jemeza will take a look asap!

**Comment by InoMurko** [comment]
@fastchain a fix has been merged: https://github.com/bobanetwork/boba/pull/1271

Care to take another try?
Thanks!

**Comment by fastchain** [comment]
@InoMurko  Hello!

Looks like nothing had changed :(

```
fraud-detector-verifier_l2geth-1  | DEBUG[10-24|09:21:15.592] Couldn't add port mapping                proto=tcp extport=30303 intport=30303 interface="UPnP or NAT-PMP" err="no UPnP or NAT-PMP router discovered"
fraud-detector-verifier_l2geth-1  | DEBUG[10-24|09:21:17.649] Served web3_clientVersion                conn=172.20.0.4:43360 reqid=0 t=55.372µs
fraud-detector-fraud-detector-1   | DEBUG 20231024T092117 Connected to VERIFIER_WEB3_URL
fraud-detector-fraud-detector-1   | Traceback (most recent call last):
fraud-detector-fraud-detector-1   |   File "./fraud-detector.py", line 134, in <module>
fraud-detector-fraud-detector-1   |     scc_addr = address_manager.functions.getAddress("StateCommitmentChain").call()
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/contract.py", line 970, in call
fraud-detector-fraud-detector-1   |     return call_contract_function(
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/contract.py", line 1564, in call_contract_function
fraud-detector-fraud-detector-1   |     return_data = web3.eth.call(
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/module.py", line 57, in caller
fraud-detector-fraud-detector-1   |     result = w3.manager.request_blocking(method_str,
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
fraud-detector-fraud-detector-1   |     response = self._make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
fraud-detector-fraud-detector-1   |     return request_func(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
fraud-detector-fraud-detector-1   |     return make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 87, in middleware
fraud-detector-fraud-detector-1   |     web3_formatters_builder(w3, method),
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/validation.py", line 140, in build_method_validators
fraud-detector-fraud-detector-1   |     w3_chain_id = w3.eth.chain_id
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/eth.py", line 632, in chain_id
fraud-detector-fraud-detector-1   |     return self._chain_id()
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/module.py", line 57, in caller
fraud-detector-fraud-detector-1   |     result = w3.manager.request_blocking(method_str,
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 197, in request_blocking
fraud-detector-fraud-detector-1   |     response = self._make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 150, in _make_request
fraud-detector-fraud-detector-1   |     return request_func(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 90, in middleware
fraud-detector-fraud-detector-1   |     return make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/buffered_gas_estimate.py", line 40, in middleware
fraud-detector-fraud-detector-1   |     return make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 94, in middleware
fraud-detector-fraud-detector-1   |     response = make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/middleware/exception_retry_request.py", line 114, in middleware
fraud-detector-fraud-detector-1   |     return make_request(method, params)
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/providers/rpc.py", line 88, in make_request
fraud-detector-fraud-detector-1   |     raw_response = make_post_request(
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/web3/_utils/request.py", line 113, in make_post_request
fraud-detector-fraud-detector-1   |     response.raise_for_status()
fraud-detector-fraud-detector-1   |   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
fraud-detector-fraud-detector-1   |     raise HTTPError(http_error_msg, response=self)
fraud-detector-fraud-detector-1   | requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://mainnet.gateway.tenderly.co/
fraud-detector-fraud-detector-1 exited with code 1
fraud-detector-verifier_dtl-1     | {"level":30,"time":1698139284929,"method":"GET","url":"/batch/transaction/latest","elapsed":5,"msg":"Served HTTP Request"}
fraud-detector-verifier_dtl-1     | {"level":30,"time":1698139284948,"method":"GET","url":"/batch/transaction/latest","elapsed":14,"msg":"Served HTTP Request"}
```

**Comment by InoMurko** [comment]
```
fraud-detector-fraud-detector-1   | requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://mainnet.gateway.tenderly.co/

```
@fastchain you might be exhausting Tenderly's public RPC?

**Comment by jemeza** [comment]
Hey @fastchain, sorry about your trouble with this. Quick question, did you remove the fraud-detector before rebuilding it? It's possible that the previous image was cached and so it didn't get rebuilt properly.
Could you:

1. Remove docker containers related to the `fraud-detector`.
2. Remove docker images related to the `fraud-detector`
3. Open `boba/ops` in a terminal window and run `docker compose build --no-cache`, wait until this finishes running
4. Open `boba/boba_community/fraud-detector` in a different terminal window and run `docker compose up` 
5. Open  `boba/boba_community/fraud-detector` in a different terminal window and run `curl -H "Content-Type: application/json" -T state-dumps/mainnet/addresses.json http://localhost:8080/addresses.json`

Let me know if you have any trouble with this.
