### ISSUE TITLE
Boba turing package misplaced

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#225]
## Issue Type
The package in [packages/boba/turing](https://github.com/bobanetwork/boba/tree/develop/packages/boba/turing)
seems to be misplaced. It's an example that needs more documentation on it's purpose.

```
[ x] bug report
[ ] feature request
```

## Current Behavior
Review the purpose and coupling of the package. Move it to examples or community - depends on the outcome of the review.

## Expected Behavior
Only core stuff that is deployed to mainnet or rinkeby in packages.

**Comment by wsdt** [comment]
On it!

**Comment by mmontour1306** [comment]
After this change I'm not able to run the examples against my local system. If I check out 'develop' as of commit 48e851f8... then the old "packages/boba/turing" tests run successfully ("yarn test:local"). At the head of 'develop', the version in boba_examples/turing-hello-world fails with:

```
  1) Turing 256 Bit Random Number
       "before all" hook for "contract should be whitelisted":
     Error: Unable to find artifact for contract: BobaTuringCredit
      at getContractDefinition (node_modules/@eth-optimism/contracts/dist/contract-defs.js:9:15)
      at getContractFactory (node_modules/@eth-optimism/contracts/dist/contract-defs.js:20:58)
      at Context.<anonymous> (test/hello-world.ts:96:38)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The turing-lending and turing-stable-swap examples are the same, while "turing-nft-random" fails with:
```
yarn run v1.22.18
$ hardhat --network boba_local test
TypeError: Member "TuringRandom" not found or not visible after argument-dependent lookup in contract ITuringHelper.
  --> contracts/ERC721min.sol:35:24:
   |
35 |       uint256 result = myHelper.TuringRandom();
   |                   

```

I also noticed that we have a few different versions of the "TuringHelper.sol" contact floating around. It would be nice to have a single authoritative instance of it.

```
$ find . -type f -name TuringHelper.sol | xargs md5sum | sort
0e257c7ea7154cd55dfda031d5d5cc57  ./boba_community/turing-monsters/contracts/TuringHelper.sol
3fb45d08af363f031b969bef13a569df  ./boba_examples/turing-complex-types/contracts/TuringHelper.sol
6af5816298fcd31d085833904e345bae  ./boba_community/turing-kyc/contracts/common/TuringHelper.sol
6af5816298fcd31d085833904e345bae  ./boba_community/turing-twitter/contracts/TuringHelper.sol
ec2f2f403954dc858ceb115073ce7a00  ./boba_community/turing-captcha-faucet/packages/contracts/contracts/TuringHelper.sol
ec2f2f403954dc858ceb115073ce7a00  ./boba_examples/turing-hello-world/contracts/TuringHelper.sol
ec2f2f403954dc858ceb115073ce7a00  ./boba_examples/turing-lending/contracts/TuringHelper.sol
ec2f2f403954dc858ceb115073ce7a00  ./boba_examples/turing-nft-random/contracts/TuringHelper.sol
ec2f2f403954dc858ceb115073ce7a00  ./boba_examples/turing-stable-swap/contracts/TuringHelper.sol
ec2f2f403954dc858ceb115073ce7a00  ./integration-tests/contracts/TuringHelper.sol
ec2f2f403954dc858ceb115073ce7a00  ./packages/boba/turing/contracts/TuringHelper.sol
eca6351d3308a7807e3540b754134ee4  ./boba_community/turing-start/packages/dapp-contracts/contracts/TuringHelper.sol

```

**Comment by wsdt** [comment]
I can't even build the current local stack on `develop`. But doesn't seem to be related to the issue above: 

**For Data Transport Layer**:
```
Error: Cannot find module '@eth-optimism/sdk'
Require stack:
- /opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js
- /opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js
- /opt/optimism/packages/data-transport-layer/dist/src/services/run.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js',
    '/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js',
    '/opt/optimism/packages/data-transport-layer/dist/src/services/run.js'
  ]
}
```

**Deployer**:
```
 "error": "ERROR processing /opt/optimism/packages/contracts/deploy/013-fund-accounts.ts:\nTypeError: L1StandardBridge.connect(...).depositETH is not a function\n    at Object.deployFn [as func] (/opt/optimism/packages/contracts/deploy/013-fund-accounts.ts:53:64)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async DeploymentsManager.executeDeployScripts (/opt/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1220:22)\n    at async DeploymentsManager.runDeploy (/opt/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)\n    at async SimpleTaskDefinition.action (/opt/optimism/node_modules/hardhat-deploy/src/index.ts:409:5)\n    at async Environment._runTaskDefinition (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)\n    at async Environment.run (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)\n    at async SimpleTaskDefinition.action (/opt/optimism/node_modules/hardhat-deploy/src/index.ts:555:32)\n    at async Environment._runTaskDefinition (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)",
  "stack": "Error: ERROR processing /opt/optimism/packages/contracts/deploy/013-fund-accounts.ts:\nTypeError: L1StandardBridge.connect(...).depositETH is not a function\n    at Object.deployFn [as func] (/opt/optimism/packages/contracts/deploy/013-fund-accounts.ts:53:64)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async DeploymentsManager.executeDeployScripts (/opt/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1220:22)\n    at async DeploymentsManager.runDeploy (/opt/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)\n    at async SimpleTaskDefinition.action (/opt/optimism/node_modules/hardhat-deploy/src/index.ts:409:5)\n    at async Environment._runTaskDefinition (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)\n    at async Environment.run (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)\n    at async SimpleTaskDefinition.action (/opt/optimism/node_modules/hardhat-deploy/src/index.ts:555:32)\n    at async Environment._runTaskDefinition (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)\n    at DeploymentsManager.executeDeployScripts (/opt/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1223:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async DeploymentsManager.runDeploy (/opt/optimism/node_modules/hardhat-deploy/src/DeploymentsManager.ts:1053:5)\n    at async SimpleTaskDefinition.action (/opt/optimism/node_modules/hardhat-deploy/src/index.ts:409:5)\n    at async Environment._runTaskDefinition (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)\n    at async Environment.run (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)\n    at async SimpleTaskDefinition.action (/opt/optimism/node_modules/hardhat-deploy/src/index.ts:555:32)\n    at async Environment._runTaskDefinition (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)\n    at async Environment.run (/opt/optimism/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)"
}
error Command failed with exit code 1.
```


Will have a look at your issue first, and then look at why the local stack itself doesn't seem to be building for me.

**Comment by wsdt** [comment]
@mmontour1306 Fixed the tests, thx!

Regarding the TuringHelper duplicates. Examples always had their own local TuringHelper duplicate. Probably to have it isolated and to make it easy to run for the community. 

But if we change this, which TuringHelper (incl. Interface) would you recommend that we are taking? The one in `packages/boba/turing/contracts/`?
