### ISSUE TITLE
Failure tests for Avalanche L2 

### ISSUE THREAD

**Issue by boyuan-chen** [bobanetwork/boba_legacy#261]
1. [Fixed]
```  1) Boba Turing Credit Test
"after all" hook for "{tag:boba} Should not increase balance for EOA accounts as helper contract address":
     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/boyuanchen/Documents/GitHub/boba.nosync/integration-tests/test/boba_turing_credit.spec.ts)
```

It's highly likely that it's a small issue.

2. 
```
   2) Boba API Tests
       Meta Transaction API Tests
         Mainnet
           {tag:boba} should swap L2 secondary token for BOBA:

      AssertionError: expected 400 to equal 201
      + expected - actual

      -400
      +201
  3) Boba API Tests
       Meta Transaction API Tests
         Mainnet
           {tag:boba} should return reverted reason from API if Boba_GasPriceOracle has insufficient BOBA:

      AssertionError: expected 'execution reverted: ERC20Permit: inva…' to equal 'execution reverted: Failed to send BO…'
      + expected - actual

      -execution reverted: ERC20Permit: invalid signature
      +execution reverted: Failed to send BOBA
  4) Boba API Tests
       Meta Transaction API Tests
         Rinkeby
           {tag:boba} should swap L2 secondary fee token for BOBA:

      AssertionError: expected 400 to equal 201
      + expected - actual

      -400
      +201
  5) Boba API Tests
       Meta Transaction API Tests
         Rinkeby
           {tag:boba} should return reverted reason from API if Boba_GasPriceOracle has insufficient BOBA:

      AssertionError: expected 'execution reverted: ERC20Permit: inva…' to equal 'execution reverted: Failed to send BO…'
      + expected - actual

      -execution reverted: ERC20Permit: invalid signature
      +execution reverted: Failed to send BOBA
  6) Boba Fee Payment Integration Tests
       Meta transaction tests
         {tag:boba} should submit the meta transaction:
     Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":5260,\"error\":{\"code\":-32000,\"message\":\"execution reverted: ERC20Permit: invalid signature\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x1\",\"from\":\"0x8db97c7cece249c2b98bdc0226cc4c2a57bf52fc\",\"to\":\"0x4200000000000000000000000000000000000024\",\"data\":\"0x3cb8dd88000000000000000000000000dae74d7327d123a1e1732c14a75599cead1aeec000000000000000000000000042000000000000000000000000000000000000240000000000000000000000000000000000000000000000003dc1936c427d00000000000000000000000000000000000000000000000000000000000062d7350e000000000000000000000000000000000000000000000000000000000000001bf83dc8fd50d578d8d155da53c1e4d96365968cd94db2395fb388905f862f84340afc30993ca243b93a6d4e86e6f53d014235633396e5e361b59647f8e749236a\"}],\"id\":5260,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:8545"},"method":"estimateGas","transaction":{"from":"0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC","gasPrice":{"type":"BigNumber","hex":"0x01"},"to":"0x4200000000000000000000000000000000000024","data":"0x3cb8dd88000000000000000000000000dae74d7327d123a1e1732c14a75599cead1aeec000000000000000000000000042000000000000000000000000000000000000240000000000000000000000000000000000000000000000003dc1936c427d00000000000000000000000000000000000000000000000000000000000062d7350e000000000000000000000000000000000000000000000000000000000000001bf83dc8fd50d578d8d155da53c1e4d96365968cd94db2395fb388905f862f84340afc30993ca243b93a6d4e86e6f53d014235633396e5e361b59647f8e749236a","accessList":null}}, tx={"data":"0x3cb8dd88000000000000000000000000dae74d7327d123a1e1732c14a75599cead1aeec000000000000000000000000042000000000000000000000000000000000000240000000000000000000000000000000000000000000000003dc1936c427d00000000000000000000000000000000000000000000000000000000000062d7350e000000000000000000000000000000000000000000000000000000000000001bf83dc8fd50d578d8d155da53c1e4d96365968cd94db2395fb388905f862f84340afc30993ca243b93a6d4e86e6f53d014235633396e5e361b59647f8e749236a","to":{},"from":"0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC","gasPrice":{"type":"BigNumber","hex":"0x01"},"type":0,"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.5.0)
  8) Boba Fee Payment Integration Tests
       Meta transaction tests
         {tag:boba} should swap secondary fee token for BOBA using secondary fee token as the fee token:
     Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":5434,\"error\":{\"code\":-32000,\"message\":\"execution reverted: ERC20Permit: invalid signature\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x1\",\"from\":\"0x8db97c7cece249c2b98bdc0226cc4c2a57bf52fc\",\"to\":\"0x4200000000000000000000000000000000000024\",\"data\":\"0x3cb8dd880000000000000000000000006b11bf72fb344260b14bf69de348277979d26b3000000000000000000000000042000000000000000000000000000000000000240000000000000000000000000000000000000000000000003dc1936c427d00000000000000000000000000000000000000000000000000000000000062d7350f000000000000000000000000000000000000000000000000000000000000001c97996277eac360abc5697a27a866194a799dc04716a1092b6d0651f7efb077ae48db8f962863f5fbcb78c9086d73904f6cbc501b70ead3ea5255aa5eadb46ab5\"}],\"id\":5434,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:8545"},"method":"estimateGas","transaction":{"from":"0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC","gasPrice":{"type":"BigNumber","hex":"0x01"},"to":"0x4200000000000000000000000000000000000024","data":"0x3cb8dd880000000000000000000000006b11bf72fb344260b14bf69de348277979d26b3000000000000000000000000042000000000000000000000000000000000000240000000000000000000000000000000000000000000000003dc1936c427d00000000000000000000000000000000000000000000000000000000000062d7350f000000000000000000000000000000000000000000000000000000000000001c97996277eac360abc5697a27a866194a799dc04716a1092b6d0651f7efb077ae48db8f962863f5fbcb78c9086d73904f6cbc501b70ead3ea5255aa5eadb46ab5","accessList":null}}, tx={"data":"0x3cb8dd880000000000000000000000006b11bf72fb344260b14bf69de348277979d26b3000000000000000000000000042000000000000000000000000000000000000240000000000000000000000000000000000000000000000003dc1936c427d00000000000000000000000000000000000000000000000000000000000062d7350f000000000000000000000000000000000000000000000000000000000000001c97996277eac360abc5697a27a866194a799dc04716a1092b6d0651f7efb077ae48db8f962863f5fbcb78c9086d73904f6cbc501b70ead3ea5255aa5eadb46ab5","to":{},"from":"0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC","gasPrice":{"type":"BigNumber","hex":"0x01"},"type":0,"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.5.0)
```

The bytecode for the AVAX token is wrong!

3.
```
  9) Liquidity Pool Test
       {tag:mrf} should fast onramp:
     Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":1703,\"error\":{\"code\":-32000,\"message\":\"exceeds block gas limit: tx gas (9000000) \\u003e current max gas (8000000)\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f8b482a86881cc849502f900850c393e6d008389544094a0706ea5cc0386eea5b8b4fa6ecb143d2019520f80b844095ea7b30000000000000000000000003c4a9b7353e37f57a91fb183d1c03032964f79f00000000000000000000000000000000000000000000000008ac7230489e80000c001a0af2cabc27ada84876d55100c3bcb66ce7c1157a89a2a75a8467ec0b408f1c815a00b5cd19109a02760bc9ad7e10a79184af8b5c080b60d328b3d8a38dffaed63c9\"],\"id\":1703,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:9650/ext/bc/C/rpc", code=SERVER_ERROR, version=web/5.5.1)
  10) Liquidity Pool Test
       Onramp batch tests
         {tag:mrf} should deposit l1 native token:
     Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":3587,\"error\":{\"code\":-32000,\"message\":\"exceeds block gas limit: tx gas (9000000) \\u003e current max gas (8000000)\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f8fc82a86881ef849502f900850c393e6d0083895440943c4a9b7353e37f57a91fb183d1c03032964f79f0888ac7230489e80000b884a44c80e30000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008ac7230489e80000c080a07562ef41318e4b78049ec17828492b20162eb3da988f3a14999cf528e950ea34a0620f92df3aea6e6aa44dc59353e54c72ee4e4e5f5bbba8be75bd7541b1df2231\"],\"id\":3587,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:9650/ext/bc/C/rpc", code=SERVER_ERROR, version=web/5.5.1)
  11) Liquidity Pool Test
       Onramp batch tests
         {tag:mrf} should depoist l1 native token and ERC20 together:
     Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":3638,\"error\":{\"code\":-32000,\"message\":\"exceeds block gas limit: tx gas (9000000) \\u003e current max gas (8000000)\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f9013c82a86881f0849502f900850c393e6d0083895440943c4a9b7353e37f57a91fb183d1c03032964f79f0888ac7230489e80000b8c4a44c80e30000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008ac7230489e800000000000000000000000000003c44deae8f4e1a034b3385b449673b795357271d0000000000000000000000000000000000000000000000008ac7230489e80000c001a05cd60e8a24ab63e868b2a5e6375bbc2ae21fc23f9c85cdc35fb540184a90f00ca041341e0e254da3bdfcbcc1d70dfa1b8707a691cbd9ce25850722b315523561d2\"],\"id\":3638,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:9650/ext/bc/C/rpc", code=SERVER_ERROR, version=web/5.5.1)
  12) Liquidity Pool Test
       Onramp batch tests
         {tag:mrf} should deposit l1 native token and three ERC20 together:
     Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":3869,\"error\":{\"code\":-32000,\"message\":\"exceeds block gas limit: tx gas (9000000) \\u003e current max gas (8000000)\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f901bd82a86881f4849502f900850c393e6d0083895440943c4a9b7353e37f57a91fb183d1c03032964f79f0888ac7230489e80000b90144a44c80e30000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008ac7230489e800000000000000000000000000003c44deae8f4e1a034b3385b449673b795357271d0000000000000000000000000000000000000000000000008ac7230489e8000000000000000000000000000020b188ae94691e9bcf1efa360f15b10bafca77420000000000000000000000000000000000000000000000008ac7230489e800000000000000000000000000007d4d845e159b10259f9569998171c45f3d67afdb0000000000000000000000000000000000000000000000008ac7230489e80000c080a0785267c1be2cbcbc25a4f0cf47df26039a84cea3fe39fbaf2e91e5bf437d189ea0685d6cf7aefa6951b737e79b2d120770cc13c2c8c093256d5e50caa3e17494cc\"],\"id\":3869,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:9650/ext/bc/C/rpc", code=SERVER_ERROR, version=web/5.5.1)
  13) Liquidity Pool Test
       Onramp batch tests
         {tag:mrf} should revert an unfulfillable swap-on in batch:
     Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":4563,\"error\":{\"code\":-32000,\"message\":\"exceeds block gas limit: tx gas (9000000) \\u003e current max gas (8000000)\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f9013e82a868820105849502f900850c393e6d0083895440943c4a9b7353e37f57a91fb183d1c03032964f79f089047cbf74ad64bcf198b8c4a44c80e30000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000047cbf74ad64bcf1980000000000000000000000003c44deae8f4e1a034b3385b449673b795357271d0000000000000000000000000000000000000000000000008ac7230489e80000c001a0d101d21f295a6720433cc8a7f9690400152c497dfa0ee0c3d6b9186736c14e1fa07ef8e94090d3db10d4351368a78d761901771a5d90248c9fc1f92bae22d209f4\"],\"id\":4563,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:9650/ext/bc/C/rpc", code=SERVER_ERROR, version=web/5.5.1)
  14) Liquidity Pool Test
       Onramp batch tests
         {tag:mrf} should revert unfulfillable swap-ons in batch:
     Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":4662,\"error\":{\"code\":-32000,\"message\":\"exceeds block gas limit: tx gas (9000000) \\u003e current max gas (8000000)\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f9017f82a868820107849502f900850c393e6d0083895440943c4a9b7353e37f57a91fb183d1c03032964f79f089047cbf74ad64bcf198b90104a44c80e30000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000047cbf74ad64bcf1980000000000000000000000003c44deae8f4e1a034b3385b449673b795357271d0000000000000000000000000000000000000000000000008ac7230489e8000000000000000000000000000020b188ae94691e9bcf1efa360f15b10bafca77420000000000000000000000000000000000000000000002445df6adcde5fc3c3cc080a083fd825da9ab4115a8911162b1293308c9e5690001066305e988f579e0f223bba019fe3cfd23fb82a5fb3fcabb94ec7d3b64cc34d0adaef20095308897f18d1170\"],\"id\":4662,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:9650/ext/bc/C/rpc", code=SERVER_ERROR, version=web/5.5.1)
15) Native BOBA Integration Tests
       {tag:other} deposit passes with a large data argument:
     Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":6019,\"error\":{\"code\":-32000,\"message\":\"oversized data tx size 49818 \\u003e max size 32768\"}}\n"
```

The L1 gas limit for Avalanche is different from other chains.

4.[Fixed]
```
  16) Replica Tests
       Matching blocks
         {tag:other} should sync a transaction:
     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/boyuanchen/Documents/GitHub/boba.nosync/integration-tests/test/replica.spec.ts)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  17) Replica Tests
       Matching blocks
         {tag:other} sync an unprotected tx (eip155):
     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/boyuanchen/Documents/GitHub/boba.nosync/integration-tests/test/replica.spec.ts)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  18) Replica Tests
       Matching blocks
         {tag:other} should forward tx to sequencer:
     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/boyuanchen/Documents/GitHub/boba.nosync/integration-tests/test/replica.spec.ts)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```
Replica issue - unknown

5. [Fixed]
```

  19) Self Destruct Tests
       Use secondary fee token as fee token
         {tag:other} should use secondary fee token as fee token:
     Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":11219,\"error\":{\"code\":-32000,\"message\":\"execution reverted: Insufficient secondary fee token balance\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x1\",\"from\":\"0xdae74d7327d123a1e1732c14a75599cead1aeec0\",\"to\":\"0x4200000000000000000000000000000000000024\",\"data\":\"0x03bb2b2d\"}],\"id\":11219,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:8545"},"method":"estimateGas","transaction":{"from":"0xdae74D7327d123a1E1732C14a75599ceAd1aeeC0","gasPrice":{"type":"BigNumber","hex":"0x01"},"to":"0x4200000000000000000000000000000000000024","data":"0x03bb2b2d","accessList":null}}, tx={"data":"0x03bb2b2d","to":{},"from":"0xdae74D7327d123a1E1732C14a75599ceAd1aeeC0","gasPrice":{"type":"BigNumber","hex":"0x01"},"type":0,"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.5.0)
      at Logger.makeError (/Users/boyuanchen/Documents/GitHub/boba.nosync/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
      at Logger.throwError (/Users/boyuanchen/Documents/GitHub/boba.nosync/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
      at /Users/boyuanchen/Documents/GitHub/boba.nosync/node_modules/@ethersproject/abstract-signer/src.ts/index.ts:301:31
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Promise.all (index 6)

  20) SSTORE tests
       Use secondary fee token as fee token
         {tag:other} should use secondary fee token as fee token:
     Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":11467,\"error\":{\"code\":-32000,\"message\":\"execution reverted: Insufficient secondary fee token balance\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x1\",\"from\":\"0xdae74d7327d123a1e1732c14a75599cead1aeec0\",\"to\":\"0x4200000000000000000000000000000000000024\",\"data\":\"0x03bb2b2d\"}],\"id\":11467,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:8545"},"method":"estimateGas","transaction":{"from":"0xdae74D7327d123a1E1732C14a75599ceAd1aeeC0","gasPrice":{"type":"BigNumber","hex":"0x01"},"to":"0x4200000000000000000000000000000000000024","data":"0x03bb2b2d","accessList":null}}, tx={"data":"0x03bb2b2d","to":{},"from":"0xdae74D7327d123a1E1732C14a75599ceAd1aeeC0","gasPrice":{"type":"BigNumber","hex":"0x01"},"type":0,"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.5.0)
      at Logger.makeError (/Users/boyuanchen/Documents/GitHub/boba.nosync/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
      at Logger.throwError (/Users/boyuanchen/Documents/GitHub/boba.nosync/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
      at /Users/boyuanchen/Documents/GitHub/boba.nosync/node_modules/@ethersproject/abstract-signer/src.ts/index.ts:301:31
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Promise.all (index 6)

  21) SSTORE tests
       Use secondary fee token as fee token
         {tag:other} should delete testInt slot storage:

      AssertionError: Expected "5001999999999999651390" to be equal 5001999999999999678689
      + expected - actual

       {
      -  "_hex": "0x010f28b1d244a7e318e1"
      +  "_hex": "0x010f28b1d244a7e2ae3e"
         "_isBigNumber": true
       }
      
      at Context.<anonymous> (test/selfdestruct.spec.ts:425:41)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  22) SSTORE tests
       Use secondary fee token as fee token
         {tag:other} should delete testArray slot storage:

      AssertionError: Expected "5001999999999999623662" to be equal 5001999999999999651390
      + expected - actual

       {
      -  "_hex": "0x010f28b1d244a7e2ae3e"
      +  "_hex": "0x010f28b1d244a7e241ee"
         "_isBigNumber": true
       }
      
      at Context.<anonymous> (test/selfdestruct.spec.ts:460:41)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Unknown

6. [Fixed]
```
  23) Turing 256 Bit Random Number Test
       "after all" hook for "should get a 256 bit random number":
     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/boyuanchen/Documents/GitHub/boba.nosync/integration-tests/test/turing.spec.ts)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```
Unknown

7. [Fixed]
```
  24) Batch Serialization
       should fetch batches:
     Error: Timeout of 80000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/boyuanchen/Documents/GitHub/boba.nosync/integration-tests/test/z-brotli-batch-serialization.spec.ts)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```
Unknown

**Comment by boyuan-chen** [comment]
@trangtran-enya Assign problem 2

**Comment by excalq** [comment]
I'm getting these same `UNPREDICTABLE_GAS_LIMIT` errors while running `BUILD=1 DAEMON=0 ./up_local.sh` on `develop`. (The `ops_boba_deployer_1` container is dying on L2ERC20 deployment tasks).

**Comment by boyuan-chen** [comment]
Hi @excalq , could you please start the local stack using 
```
$ cd ops
$ yarn install
$ yarn build
$ docker-compose -f docker-compose.yml build
$ docker-compose -f docker-compose.yml up -V
```
?
