### ISSUE TITLE
[integration tests] flaky metatransaction tests

### ISSUE THREAD

**Issue by InoMurko** [bobanetwork/boba_legacy#530]
## Issue Type

```
[x ] bug report
[ ] feature request
```

## Current Behavior
```
107 passing (11m)
  2 failing

  1) Boba API Tests
       Meta Transaction API Tests
         Mainnet and Rinkeby
           should swap BOBA for ETH:

      AssertionError: expected 400 to equal 201
      + expected - actual

      -400
      +201
      
      at Context.<anonymous> (test/boba-api.spec.ts:116:40)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

  2) Boba API Tests
       Meta Transaction API Tests
         Mainnet and Rinkeby
           should return reverted reason from API if Boba_GasPriceOracle has insufficient ETH:
     TypeError: Cannot read properties of undefined (reading 'error')
      at Context.<anonymous> (test/boba-api.spec.ts:293:59)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)


```

## Expected Behavior
These tests should be hardened

## Steps to Reproduce

1. Flaky integration tests
2. Order of tests:
```
../integration-tests/test/stress-tests.spec.ts
../integration-tests/test/pool_dao_actions.spec.ts
../integration-tests/test/bridged-tokens.spec.ts
../integration-tests/test/routed_exit_fee.spec.ts
../integration-tests/test/replica.spec.ts
../integration-tests/test/erc20bridge.spec.ts
../integration-tests/test/boba-fee-payment.spec.ts
../integration-tests/test/queue-ingestion.spec.ts
../integration-tests/test/xBoba.spec.ts
../integration-tests/test/boba-api.spec.ts
../integration-tests/test/basic_nft.spec.ts
../integration-tests/test/hardfork.spec.ts
../integration-tests/test/contracts.spec.ts
../integration-tests/test/selfdestruct.spec.ts
../integration-tests/test/whitelist.spec.ts

```
## Suggested Fix
/

**Comment by boyuan-chen** [comment]
closed #534
